sudo: required
services:
  - docker

before_install:
  - docker build -t 20742074/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 20742074/react-test npm test -- --coverage

after_success:
  - docker build -t 20742074/multi-client ./client
  - docker build -t 20742074/multi-nginx ./nginx
  - docker build -t 20742074/multi-server ./server
  - docker build -t 20742074/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 20742074/multi-client
  - docker push 20742074/multi-nginx
  - docker push 20742074/multi-server
  - docker push 20742074/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-261900186654
  backer_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY